name: workflow
on:
 workflow_dispatch:
   inputs:
     param1:
        description: 'Enter value for parameter 1'
        required: true
     param2:
        description: 'Enter value for parameter 2'
        required: false
